{% set version = "1.8-0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-weightedcluster
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/WeightedCluster_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/WeightedCluster/WeightedCluster_{{ version }}.tar.gz
  sha256: a046c857f8bc5d8bf25d83feb18004f23b34121080692e328354779172f9eae9

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcolorbrewer
    - r-traminer >=2.0_6
    - r-cluster
    - r-dofuture
    - r-fastcluster
    - r-foreach
    - r-future
    - r-nnet
    - r-progressr
    - r-vegclust
  run:
    - r-base
    - r-rcolorbrewer
    - r-traminer >=2.0_6
    - r-cluster
    - r-dofuture
    - r-fastcluster
    - r-foreach
    - r-future
    - r-nnet
    - r-progressr
    - r-vegclust

test:
  commands:
    - $R -e "library('WeightedCluster')"           # [not win]
    - "\"%R%\" -e \"library('WeightedCluster')\""  # [win]

about:
  home: http://mephisto.unige.ch/weightedcluster
  license: GPL-2.0-or-later
  summary: Clusters state sequences and weighted data. It provides an optimized weighted PAM algorithm as well as functions for aggregating replicated cases, computing cluster quality measures for a range of clustering solutions and plotting clusters of state sequences.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - tobiasraabe
