{% set version = "1.6-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-weightedcluster
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/WeightedCluster_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/WeightedCluster/WeightedCluster_{{ version }}.tar.gz
  sha256: e1e1fd01f15f76e60eec98772725997d52354035c3a4bd1ad95da52a7df2f21d

build:
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-cluster
    - r-dofuture
    - r-foreach
    - r-future
    - r-progressr
    - r-rcolorbrewer
    - r-traminer >=2.0_6
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-cluster
    - r-dofuture
    - r-foreach
    - r-future
    - r-progressr
    - r-rcolorbrewer
    - r-traminer >=2.0_6

test:
  commands:
    - $R -e "library('WeightedCluster')"           # [not win]
    - "\"%R%\" -e \"library('WeightedCluster')\""  # [win]

about:
  home: http://mephisto.unige.ch/weightedcluster
  license: GPL-2.0-or-later
  summary: Clusters state sequences and weighted data. It provides an optimized weighted PAM algorithm as well as functions for aggregating replicated cases, computing cluster quality measures for a range of clustering solutions and plotting clusters of state sequences.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - tobiasraabe
